---
schema:
  procedures: {}
  tables:
    ingredients:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        content:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: content
          order: 3
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
      indices: []
      name: ingredients
      options: []
      order: 1
    recipe_ingredients:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - recipe_id
            - ingredient_id
          match_type: ''
          name: recipe_ingredients_recipe_id_ingredient_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - ingredient_id
          match_type: ''
          name: recipe_ingredients_fk_ingredient_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: ingredients
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - recipe_id
          match_type: ''
          name: recipe_ingredients_fk_recipe_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: recipes
          type: FOREIGN KEY
      fields:
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        ingredient_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: ingredient_id
          order: 3
          size:
            - 0
        recipe_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: recipe_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - ingredient_id
          name: recipe_ingredients_idx_ingredient_id
          options: []
          type: NORMAL
        - fields:
            - recipe_id
          name: recipe_ingredients_idx_recipe_id
          options: []
          type: NORMAL
      name: recipe_ingredients
      options: []
      order: 3
    recipes:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        content:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: content
          order: 3
          size:
            - 0
        created:
          data_type: timestamp
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: created
          order: 4
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 0
        updated:
          data_type: timestamp
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: updated
          order: 5
          size:
            - 0
      indices: []
      name: recipes
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Ingredient
      - Recipe
      - RecipeIngredient
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11016
